export const databaseKey = {
    user: ["Name", "Email", "Mobile"],
    application: ["ExaminationType", "Status", "ExaminationCourseId", "TargetSchoolId", "TargetCollegeId","TargetMajorId", "ApproveComment"],
    examinationschedule: ["Type", "Name", "StartTime", "EndTime", "Address", "Remarks", "PersonInCharge", "Mobile", "OfficeTel"],
    examinationgroup: ["UserId", "SchoolId", "MajorId","CollegeId", "Order", "Remarks"],
    examinationresult: ["TargetMajorId","TargetSchoolId","IfCome", "WrittenScore", "InterviewScore", "ExaminationScore", "TotalScore", "IfEnroll", "AdminComment"],
    FirstTrialDataBase: [
        { name: "user", id: "1", cascadeId: "1" },
        { name: "application", id: "2", cascadeId: "2" }
    ],//初审节点
    ScheduleBase: [
        { name: "user", id: "1", cascadeId: "1" },
        { name: "examinationschedule", id: "3", cascadeId: "3" },
        { name: "examinationgroup", id: "4", cascadeId: "4" }
    ],//复试安排节点
    ResultBase: [
        { name: "user", id: "1", cascadeId: "1" },
        { name: "examinationresult", id: "5", cascadeId: "5" },
    ],//复试结果节点
    OtherBase: [
        { name: "user", id: "1", cascadeId: "1" },
    ],//其他节点
    dataBase: [
        { name: "user", id: "1", cascadeId: "1"},
        { name: "application", id: "2", cascadeId:"2"},
        { name: "examinationschedule", id: "3", cascadeId: "3"},
        { name: "examinationgroup", id: "4", cascadeId: "4" },
        { name: "examinationresult", id: "5", cascadeId: "5" },
    ],
    FirstTrialKey: [
        { name: "Name", parentId: "1" },
        { name: "Email", parentId: "1" },
        { name: "Mobile", parentId: "1" },
        { name: "ExaminationType", parentId: "2" },
        { name: "Status", parentId: "2" },
        { name: "ExaminationCourseId", parentId: "2" },
        { name: "TargetSchoolId", parentId: "2" },
        { name: "TargetCollegeId", parentId: "2" },
        { name: "ApproveComment", parentId: "2" },
    ],
    ScheduleKey: [
        { name: "Name", parentId: "1" },
        { name: "Email", parentId: "1" },
        { name: "Mobile", parentId: "1" },
        { name: "Type", parentId: "3" },
        { name: "Name", parentId: "3" },
        { name: "StartTime", parentId: "3" },
        { name: "EndTime", parentId: "3" },
        { name: "Address", parentId: "3" },
        { name: "Remarks", parentId: "3" },
        { name: "PersonInCharge", parentId: "3" },
        { name: "Mobile", parentId: "3" },
        { name: "OfficeTel", parentId: "3" },
        { name: "SchoolId", parentId: "4" },
        { name: "CollegeId", parentId: "4" },
        { name: "MajorId", parentId: "4" },
        { name: "Type", parentId: "4" },
        { name: "Name", parentId: "4" },
        { name: "StartTime", parentId: "4" },
        { name: "EndTime", parentId: "4" },
        { name: "Adress", parentId: "4" },
        { name: "Remarks", parentId: "4" },
        { name: "PersonInCharge", parentId: "4" },
        { name: "Mobile", parentId: "4" },
        { name: "OfficeTel", parentId: "4" },
    ],
    ResultKey: [
        { name: "Name", parentId: "1" },
        { name: "Email", parentId: "1" },
        { name: "Mobile", parentId: "1" },
        { name: "IfCome", parentId: "5" },
        { name: "WrittenScore", parentId: "5" },
        { name: "InterviewScore", parentId: "5" },
        { name: "ExaminationScore", parentId: "5" },
        { name: "TotalScore", parentId: "5" },
        { name: "IfEnroll", parentId: "5" },
        { name: "AdminComment", parentId: "5" },
    ],
    OtherKey: [
        { name: "Name", parentId: "1" },
        { name: "Email", parentId: "1" },
        { name: "Mobile", parentId: "1" },
    ],
    key: [
        { name: "Name", parentId: "1" },
        { name: "Email", parentId: "1" },
        { name: "Mobile", parentId: "1" },
        { name: "ExaminationType", parentId: "2" },
        { name: "Status", parentId: "2" },
        { name: "ExaminationCourseId", parentId: "2" },
        { name: "TargetSchoolId", parentId: "2" },
        { name: "TargetCollegeId", parentId: "2" },
        { name: "ApproveComment", parentId: "2" },
        { name: "Type", parentId: "3" },
        { name: "Name", parentId: "3" },
        { name: "StartTime", parentId: "3" },
        { name: "EndTime", parentId: "3" },
        { name: "Address", parentId: "3" },
        { name: "Remarks", parentId: "3" },
        { name: "PersonInCharge", parentId: "3" },
        { name: "Mobile", parentId: "3" },
        { name: "OfficeTel", parentId: "3" },
        { name: "SchoolId", parentId: "4" },
        { name: "CollegeId", parentId: "4" },
        { name: "MajorId", parentId: "4" },
        { name: "Type", parentId: "4" },
        { name: "Name", parentId: "4" },
        { name: "StartTime", parentId: "4" },
        { name: "EndTime", parentId: "4" },
        { name: "Adress", parentId: "4" },
        { name: "Remarks", parentId: "4" },
        { name: "PersonInCharge", parentId: "4" },
        { name: "Mobile", parentId: "4" },
        { name: "OfficeTel", parentId: "4" },
        { name: "IfCome", parentId: "5" },
        { name: "WrittenScore", parentId: "5" },
        { name: "InterviewScore", parentId: "5" },
        { name: "ExaminationScore", parentId: "5" },
        { name: "TotalScore", parentId: "5" },
        { name: "IfEnroll", parentId: "5" },
        { name: "AdminComment", parentId: "5" },
    ]
}